### PR TITLE
The host should not contain https

### PR DESCRIPTION
**Pull request by OskarStark**

### CODE REVIEW

**Comment by JamesHemery** [comment]
Hi Oskar, 

Good remark ! I'll just put back the `www.` indicated by the Spot-Hit documentation.

**Comment by OskarStark** [comment]
Thanks, would you be interested to contribute your 2 bridges to symfony?

**Comment by JamesHemery** [comment]
Yes, of course.

**Comment by OskarStark** [comment]
Oh great 🥰

**Comment by JamesHemery** [comment]
@OskarStark Do I have something to do for this?

**Comment by OskarStark** [comment]
Yes create a PR on Symfony/Symfony repo. Do you need any help?

**Comment by JamesHemery** [comment]
Ok thanks. No it's ok, I'll see that this weekend.

**Comment by OskarStark** [comment]
Amazing, thanks!

**Pull request merged**
